# Generated by Django 2.0.13 on 2020-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
