# Generated by Django 2.0.13 on 2020-01-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_if_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_active',
            new_name='is_active',
        ),
    ]
